# Generated by Django 6.0.3 on 2026-03-12 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_teacher_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['-created_at', '-updated_at', 'surname']},
        ),
    ]
