# Generated by Django 6.0.3 on 2026-03-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_alter_teacher_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='yoga_types',
            field=models.ManyToManyField(related_name='teachers', to='classes.yoga_type'),
        ),
    ]
