# Generated by Django 6.0.3 on 2026-03-12 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_teacher_slug_teacher_yoga_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name='Yoga_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('repeats_weekly', models.BooleanField(default=False)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='classes.teacher')),
                ('yoga_types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='classes.yoga_type')),
            ],
            options={
                'verbose_name_plural': 'Yoga Classes',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
