# Generated by Django 6.0.3 on 2026-03-16 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_alter_teacher_slug_yoga_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yoga_class',
            options={'ordering': ['date', 'start_time', 'yoga_types__title'], 'verbose_name_plural': 'Yoga Classes'},
        ),
    ]
