# Generated by Django 6.0.3 on 2026-04-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_alter_yoga_class_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='yoga_class',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
    ]
