# Generated by Django 6.0.3 on 2026-03-18 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_account',
            name='phone',
        ),
    ]
