from django.db import models
from accounts.models import User_Account
from classes.models import Yoga_Class
# Create your models here.
BOOKING_STATUS_CHOICES = [
    (0, 'Pending'),
    (1, 'Confirmed'),
    (2, 'Cancelled'),
]
class Booking(models.Model):
    user = models.ForeignKey("accounts.User_Account", verbose_name="User", on_delete=models.CASCADE) #create a foreign key relationship between Booking and User models, with a related name of 'bookings' for reverse lookups (the unique=True argument ensures that each user can only have one booking, which is necessary to prevent multiple bookings for the same class by the same user)
    yoga_class = models.ForeignKey("classes.Yoga_Class", verbose_name="Yoga Class", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    cancelled_at = models.DateTimeField(null=True, blank=True)
    stripe_payment_intent = models.CharField(max_length=255, null=True, blank=True) #add a field to store the Stripe payment intent ID for each booking, which will be used to track the payment status of the booking and to handle cancellations and refunds if necessary (the field is optional because it will only be populated for bookings that have been paid for, and it can be null or blank for bookings that are created but not yet paid for)
    stripe_checkout_id = models.CharField(max_length=255, null=True, blank=True, unique=True) #add a field to store the Stripe checkout session ID for each booking, which will be used to track the payment status of the booking and to handle cancellations and refunds if necessary (the field is optional because it will only be populated for bookings that have been paid for, and it can be null or blank for bookings that are created but not yet paid for)
    amount_paid = models.DecimalField(max_digits=4, decimal_places=2, null=True, blank=True) #add a field to store the amount paid for each booking, which will be used to track the revenue generated by the bookings and to handle cancellations and refunds if necessary (the field is optional because it will only be populated for bookings that have been paid for, and it can be null or blank for bookings that are created but not yet paid for)
    status = models.IntegerField(choices=BOOKING_STATUS_CHOICES, default=0)
    currency = models.CharField(max_length=10, default='GBP') #add a field to store the currency of the payment for each booking, which will be used to handle payments in different currencies and to display the correct currency symbol in the user interface (the field has a default value of 'USD' but it can be changed if you want to support other currencies)

    class Meta:
        unique_together = ('user', 'yoga_class') #add a unique constraint to the combination of user and yoga_class fields, which ensures that each user can only have one booking for each yoga class (this is necessary to prevent multiple bookings for the same class by the same user)
        ordering = ['-created_at']
        #create ordering by newest created_at first
    
    def __str__(self):
        return f'Booking for {self.user.get_full_name()} - {self.yoga_class} - Status: {self.get_status_display()}'