# Generated by Django 6.0.3 on 2026-04-03 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_user_account_phone'),
        ('classes', '0009_alter_yoga_class_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_checkout_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Confirmed'), (2, 'Cancelled')], default=0)),
                ('currency', models.CharField(default='GBP', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user_account', verbose_name='User')),
                ('yoga_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.yoga_class', verbose_name='Yoga Class')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'yoga_class')},
            },
        ),
    ]
